version: '3'

services:
  nodeapp:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '7698:7698'
    volumes:
      - .:/usr/src/app
      - node_modules
    env_file: .env
    depends_on: 
      - mongo-database
    networks:
      - node-app-network
  mongo-database:
    image: 'mongo'
    restart: unless-stopped
    ports:
      - '27018:27017'
    volumes:
      - ./mongo_db:/data/db
    networks:
      - node-app-network

networks:
  node-app-network:
    driver: bridge